language: python
matrix:
  include:
  - python: '2.7'
    env: TOXENV=py27
  - python: '2.7'
    env: TOXENV=lint
  - python: '3.6'
    env: TOXENV=py36
  fast_finish: true
install:
  - pip install tox
script:
  - tox -e $TOXENV
