language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - pylint --errors-only --rcfile=.pylintrc --output-format=colorized *.py
  - nosetests --cover-package=log_symbols --with-coverage --cover-erase  --cover-html --cover-branches
